---

  - name: ASM-storage | run kpartx to add partition
    shell: kpartx -a {{ item.1.device}}
    args:
     creates: "{{ item.1.device}}p1"
    with_subelements: 
      - asm_diskgroups
      - disk
    tags: kpartx