---

  master_node: true
  role_separation: false
  hostgroup: default
  configure_cluster: false
  oracle_psu_apply_gi: true

  oracle_user: oracle                        # User that will own the Oracle Installations.
  grid_user: grid
  grid_install_user: "{% if role_separation==true %}{{ grid_user }} {% else %}{{ oracle_user }}{% endif %}" 
  oracle_user_home: "/home/{{ oracle_user }}" # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
  grid_user_home: "/home/{{ grid_install_user }}" # Home directory for oracle_user. Needed for passing in ssh-keys, profiles etc
  oracle_group: oinstall                          # Primary group for oracle_user. 

  oracle_sw_source_www: http://www/orasw     # address to all software if using the get_url module when putting software on the host(s)
  oracle_sw_source_local: /tmp  # Path to all software if using the copy module when putting software on the host(s)
  is_sw_source_local: true
  install_from_nfs: false
  oracle_sw_copy: "{% if install_from_nfs==True %}False{% else %}True{% endif %}"
  oracle_sw_unpack: "{% if install_from_nfs==True %}False{% else %}True{% endif %}"
  install_from_nfs: false
  nfs_server_sw: nfsserver
  nfs_server_sw_path: /path/to/orasw

  oracle_stage: /u01/stage
  oracle_stage_remote: "{{ oracle_stage }}"
  oracle_stage_install: "{% if oracle_sw_copy=='False' and oracle_sw_unpack=='False'%}{{ oracle_stage_remote }}{% else %}{{ oracle_stage }}{% endif %}"
  oracle_base: /u01/app/oracle
  oracle_rsp_stage: "{{ oracle_stage }}/rsp"
  oracle_psu_stage: "{{ oracle_stage }}/psu"
  oracle_inventory_loc: /u01/app/oraInventory
  oracle_home_gi: "{% if configure_cluster==True %}{{ oracle_home_gi_cl }}{% else %}{{ oracle_home_gi_so }}{% endif %}"
  oracle_home_gi_cl: "/u01/app/{{ oracle_install_version_gi }}/grid" # ORACLE_HOME for Grid Infrastructure (Clustered)
  oracle_home_gi_so: "{{ oracle_base }}/{{ oracle_install_version_gi }}/grid" # ORACLE_HOME for Grid Infrastructure (Stand Alone)

  oracle_hostname: "{{ ansible_fqdn }}"                            # Full (FQDN) name of the host


  oracle_sw_image_gi_psu:                                              # Files containing the installation media for Grid Infrastructure 
       #- { filename: p19392646_121020_Linux-x86-64.zip, patchid: 19392646, version: 12.1.0.2, patchversion: 12.1.0.2.1, description: GI-PSU-Oct-2014 }
       #- { filename: p20485724_121020_Linux-x86-64.zip, patchid: 20485724, version: 12.1.0.2, patchversion: 12.1.0.2.3, description: GI-PSU-Apr-2015 }
       - { filename: p21523234_121020_Linux-x86-64.zip, patchid: 21523234, version: 12.1.0.2, patchversion: 12.1.0.2.5, description: GI-PSU-Oct-2015 }
       #- { filename: p19380115_112040_Linux-x86-64.zip, patchid: 19380115, version: 11.2.0.4, patchversion: 11.2.0.4.4, description: GI-PSU-Oct-2014 }
       - { filename: p20485808_112040_Linux-x86-64.zip, patchid: 20485808, version: 11.2.0.4, patchversion: 11.2.0.4.6, description: GI-PSU-Apr-2015 }
       


  oracle_opatch_patch:
       - { filename: p6880880_121010_Linux-x86-64.zip, version: 12.1.0.2 }
       - { filename: p6880880_121010_Linux-x86-64.zip, version: 12.1.0.1 }
       - { filename: p6880880_112000_Linux-x86-64.zip, version: 11.2.0.4 }
       - { filename: p6880880_112000_Linux-x86-64.zip, version: 11.2.0.3 }

