---

  oracle_home_db: "{{ oracle_base }}/{{ item.oracle_version_db }}/{{ item.home }}"      # ORACLE_HOME path
  oracle_home_db_install: "{{ oracle_base }}/{{ item.oracle_version_db }}/{{ item.home }}" # This is only used when installing the db server and creating the databases
  oracle_stage: /u01/stage
  oracle_rsp_stage: "{{ oracle_stage }}/rsp"
  oracle_inventory_loc: /u01/app/oraInventory
  oracle_base: /u01/app/oracle



